version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: budget-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: budget-postgres-data
