export const PRIMARY_USES = [
  { value: "personal", label: "Personal finances only" },
  { value: "business", label: "Business/freelance finances only" },
  { value: "both", label: "Both personal and business" },
] as const;

export const WORK_TYPES = [
  { value: "employed", label: "Employed (salary/hourly)" },
  { value: "self_employed", label: "Self-employed / Freelancer" },
  { value: "business_owner", label: "Business owner" },
  { value: "student", label: "Student" },
  { value: "retired", label: "Retired" },
  { value: "unemployed", label: "Not currently working" },
] as const;

export const INDUSTRIES = [
  {
    value: "tech",
    label: "Technology / Software",
    keywords: [
      "programming",
      "developer",
      "engineer",
      "IT",
      "startup",
      "SaaS",
      "web",
      "mobile",
      "app",
      "coding",
      "computer",
      "data",
      "AI",
      "machine learning",
      "cybersecurity",
      "devops",
      "cloud",
    ],
  },
  {
    value: "healthcare",
    label: "Healthcare / Medical",
    keywords: [
      "doctor",
      "nurse",
      "hospital",
      "clinic",
      "pharma",
      "pharmaceutical",
      "dentist",
      "therapist",
      "mental health",
      "wellness",
      "medical",
      "health",
      "patient",
      "care",
      "veterinary",
      "vet",
    ],
  },
  {
    value: "finance",
    label: "Finance / Banking",
    keywords: [
      "bank",
      "investment",
      "trading",
      "stock",
      "insurance",
      "accounting",
      "accountant",
      "CPA",
      "bookkeeper",
      "tax",
      "audit",
      "financial",
      "wealth",
      "assets",
      "portfolio",
      "fintech",
      "crypto",
    ],
  },
  {
    value: "education",
    label: "Education / Teaching",
    keywords: [
      "teacher",
      "professor",
      "tutor",
      "school",
      "university",
      "college",
      "training",
      "coaching",
      "instructor",
      "academic",
      "learning",
      "e-learning",
      "curriculum",
      "student",
    ],
  },
  {
    value: "legal",
    label: "Legal / Law",
    keywords: [
      "lawyer",
      "attorney",
      "paralegal",
      "law firm",
      "litigation",
      "contract",
      "compliance",
      "legal",
      "court",
      "judge",
      "notary",
      "patent",
      "trademark",
      "IP",
    ],
  },
  {
    value: "creative",
    label: "Creative / Design",
    keywords: [
      "designer",
      "graphic",
      "UI",
      "UX",
      "artist",
      "illustrator",
      "animator",
      "motion",
      "3D",
      "branding",
      "creative",
      "visual",
      "art",
      "photography",
      "photographer",
      "video",
      "film",
    ],
  },
  {
    value: "marketing",
    label: "Marketing / Advertising",
    keywords: [
      "marketing",
      "advertising",
      "ads",
      "SEO",
      "SEM",
      "social media",
      "content",
      "copywriter",
      "PR",
      "public relations",
      "brand",
      "digital marketing",
      "growth",
      "campaign",
      "influencer",
    ],
  },
  {
    value: "sales",
    label: "Sales / Business Development",
    keywords: [
      "sales",
      "account executive",
      "business development",
      "BDR",
      "SDR",
      "closer",
      "enterprise",
      "B2B",
      "B2C",
      "commission",
      "quota",
      "CRM",
      "lead",
    ],
  },
  {
    value: "consulting",
    label: "Consulting / Advisory",
    keywords: [
      "consultant",
      "advisor",
      "strategy",
      "management consulting",
      "business consultant",
      "freelance consultant",
      "expert",
      "specialist",
    ],
  },
  {
    value: "real_estate",
    label: "Real Estate / Property",
    keywords: [
      "realtor",
      "agent",
      "broker",
      "property",
      "housing",
      "mortgage",
      "landlord",
      "rental",
      "commercial real estate",
      "residential",
      "leasing",
      "investment property",
    ],
  },
  {
    value: "construction",
    label: "Construction / Trades",
    keywords: [
      "contractor",
      "builder",
      "carpenter",
      "electrician",
      "plumber",
      "HVAC",
      "roofing",
      "painting",
      "renovation",
      "remodeling",
      "handyman",
      "mason",
      "welder",
      "mechanic",
    ],
  },
  {
    value: "manufacturing",
    label: "Manufacturing / Industrial",
    keywords: [
      "factory",
      "production",
      "assembly",
      "industrial",
      "engineering",
      "machinery",
      "supply chain",
      "logistics",
      "warehouse",
      "quality control",
    ],
  },
  {
    value: "retail",
    label: "Retail / E-commerce",
    keywords: [
      "store",
      "shop",
      "ecommerce",
      "online store",
      "merchant",
      "seller",
      "inventory",
      "wholesale",
      "dropshipping",
      "Amazon",
      "Shopify",
      "boutique",
    ],
  },
  {
    value: "hospitality",
    label: "Hospitality / Tourism",
    keywords: [
      "hotel",
      "restaurant",
      "bar",
      "cafe",
      "tourism",
      "travel",
      "event",
      "catering",
      "chef",
      "cook",
      "bartender",
      "server",
      "hospitality",
      "Airbnb",
      "vacation",
    ],
  },
  {
    value: "food",
    label: "Food / Beverage",
    keywords: [
      "food",
      "beverage",
      "restaurant",
      "bakery",
      "coffee",
      "brewery",
      "winery",
      "food truck",
      "catering",
      "meal prep",
      "nutrition",
      "diet",
    ],
  },
  {
    value: "entertainment",
    label: "Entertainment / Media",
    keywords: [
      "music",
      "musician",
      "actor",
      "film",
      "movie",
      "TV",
      "streaming",
      "podcast",
      "radio",
      "gaming",
      "esports",
      "content creator",
      "YouTuber",
      "influencer",
      "entertainment",
    ],
  },
  {
    value: "sports",
    label: "Sports / Fitness",
    keywords: [
      "gym",
      "fitness",
      "personal trainer",
      "coach",
      "athlete",
      "sports",
      "yoga",
      "pilates",
      "CrossFit",
      "martial arts",
      "dance",
      "swimming",
      "running",
    ],
  },
  {
    value: "beauty",
    label: "Beauty / Wellness",
    keywords: [
      "salon",
      "spa",
      "hair",
      "stylist",
      "barber",
      "makeup",
      "esthetician",
      "nail",
      "skincare",
      "cosmetics",
      "massage",
      "beauty",
    ],
  },
  {
    value: "agriculture",
    label: "Agriculture / Farming",
    keywords: [
      "farm",
      "farming",
      "agriculture",
      "livestock",
      "crops",
      "organic",
      "ranch",
      "vineyard",
      "forestry",
      "fishing",
      "aquaculture",
    ],
  },
  {
    value: "transportation",
    label: "Transportation / Logistics",
    keywords: [
      "trucking",
      "shipping",
      "delivery",
      "courier",
      "freight",
      "logistics",
      "driver",
      "Uber",
      "Lyft",
      "taxi",
      "fleet",
      "moving",
      "storage",
    ],
  },
  {
    value: "nonprofit",
    label: "Nonprofit / NGO",
    keywords: [
      "nonprofit",
      "charity",
      "NGO",
      "foundation",
      "volunteer",
      "social",
      "community",
      "advocacy",
      "fundraising",
      "donation",
      "mission",
    ],
  },
  {
    value: "government",
    label: "Government / Public Sector",
    keywords: [
      "government",
      "public",
      "federal",
      "state",
      "municipal",
      "civil service",
      "military",
      "defense",
      "policy",
      "administration",
    ],
  },
  {
    value: "science",
    label: "Science / Research",
    keywords: [
      "research",
      "scientist",
      "laboratory",
      "biotech",
      "chemistry",
      "physics",
      "biology",
      "R&D",
      "clinical",
      "academic research",
    ],
  },
  {
    value: "energy",
    label: "Energy / Utilities",
    keywords: [
      "energy",
      "oil",
      "gas",
      "solar",
      "renewable",
      "wind",
      "electric",
      "utility",
      "power",
      "mining",
      "environmental",
    ],
  },
  {
    value: "hr",
    label: "Human Resources / Recruiting",
    keywords: [
      "HR",
      "human resources",
      "recruiting",
      "recruiter",
      "staffing",
      "talent",
      "headhunter",
      "hiring",
      "payroll",
      "benefits",
    ],
  },
  {
    value: "writing",
    label: "Writing / Publishing",
    keywords: [
      "writer",
      "author",
      "editor",
      "journalist",
      "blogger",
      "copywriter",
      "technical writer",
      "publishing",
      "book",
      "magazine",
      "news",
      "content",
    ],
  },
  {
    value: "architecture",
    label: "Architecture / Interior Design",
    keywords: [
      "architect",
      "interior design",
      "landscape",
      "urban planning",
      "CAD",
      "blueprint",
      "building design",
      "space planning",
    ],
  },
  {
    value: "insurance",
    label: "Insurance",
    keywords: [
      "insurance",
      "agent",
      "broker",
      "underwriter",
      "claims",
      "actuary",
      "life insurance",
      "health insurance",
      "auto insurance",
      "property insurance",
    ],
  },
  {
    value: "telecom",
    label: "Telecommunications",
    keywords: [
      "telecom",
      "telecommunications",
      "mobile",
      "wireless",
      "network",
      "internet",
      "ISP",
      "cable",
      "fiber",
      "5G",
    ],
  },
  {
    value: "cleaning",
    label: "Cleaning / Janitorial",
    keywords: [
      "cleaning",
      "janitorial",
      "housekeeping",
      "maid",
      "custodian",
      "sanitation",
      "pressure washing",
      "window cleaning",
      "carpet cleaning",
    ],
  },
  {
    value: "childcare",
    label: "Childcare / Education",
    keywords: [
      "childcare",
      "daycare",
      "nanny",
      "babysitter",
      "preschool",
      "early childhood",
      "au pair",
      "pediatric",
    ],
  },
  {
    value: "pet",
    label: "Pet Services",
    keywords: [
      "pet",
      "dog",
      "cat",
      "grooming",
      "pet sitting",
      "dog walking",
      "boarding",
      "training",
      "pet store",
    ],
  },
  {
    value: "home_services",
    label: "Home Services",
    keywords: [
      "home improvement",
      "landscaping",
      "lawn care",
      "pool",
      "pest control",
      "security",
      "locksmith",
      "appliance repair",
      "home automation",
    ],
  },
  {
    value: "automotive",
    label: "Automotive",
    keywords: [
      "auto",
      "car",
      "dealership",
      "mechanic",
      "body shop",
      "detailing",
      "auto parts",
      "tire",
      "oil change",
      "collision",
    ],
  },
  {
    value: "fashion",
    label: "Fashion / Apparel",
    keywords: [
      "fashion",
      "clothing",
      "apparel",
      "textile",
      "garment",
      "accessories",
      "jewelry",
      "footwear",
      "luxury",
      "boutique",
    ],
  },
];
